version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "./grafana-prometheus.yaml:/usr/share/grafana/conf/provisioning/datasources/"
      - "./grafana.ini:/usr/share/grafana/conf/defaults.ini"
  net_test:
    build: .
    ports:
      - "2112:2112"
  # debug:
  #   image: alpine
