OUT=analyse
SRC=analyse.c

# analyse compiles the analyse tool
# Arguments:
#	- GCC_FLAGS (Optional): Will be passed into GCC at compile time
analyse: analyse.c
	gcc ${GCC_FLAGS} -o "${OUT}" "${SRC}"
